### ISSUE TITLE
runtime error in training process

### ISSUE THREAD

**Issue by leexian** [memray/seq2seq-keyphrase#12]
Traceback (most recent call last):
  File "keyphrase_copynet.py", line 262, in <module>
    agent.compile_('all')
  File "/home/developer/seq2seq-keyphrase/emolga/models/covc_encdec.py", line 1849, in compile_
    self.compile_train()
  File "/home/developer/seq2seq-keyphrase/emolga/models/covc_encdec.py", line 1880, in compile_train
    logPxz, logPPL     = self.decoder.build_decoder(target, cc_matrix, code, c_mask)
  File "/home/developer/seq2seq-keyphrase/emolga/models/covc_encdec.py", line 996, in build_decoder
    non_sequences=[context, c_mask, context_A]
  File "/home/developer/anaconda3/lib/python3.6/site-packages/theano/scan_module/scan.py", line 1076, in scan
    scan_outs = local_op(*scan_inputs)
  File "/home/developer/anaconda3/lib/python3.6/site-packages/theano/gof/op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/home/developer/anaconda3/lib/python3.6/site-packages/theano/scan_module/scan_op.py", line 546, in make_node
    inner_sitsot_out.type.dtype))
ValueError: When compiling the inner function of scan the following error has been encountered: The initial state (`outputs_info` in scan nomenclature) of variable IncSubtensor{Set;:int64:}.0 (argument number 5) has dtype float32, while the result of the inner function (`fn`) has dtype float64. This can happen if the inner function of scan results in an upcast or downcast.

**Comment by leexian** [comment]
I got the above runtime error when I tried the training process. How can I fix that dtype mismatch error?

**Comment by Taosky** [comment]
Set theano flags to float32.
Run  `THEANO_FLAGS='floatX=float32' python keyphrase/keyphrase_copynet.py`.

**Comment by memray** [comment]
@Taosky is correct. Also, you can create a config file .theanorc like [this](http://deeplearning.net/software/theano/library/config.html#envvar-THEANORC)  for convenience.
